// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// Logger is an autogenerated mock type for the Logger type
type Logger struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Logger) Close() {
	_m.Called()
}

// Log provides a mock function with given fields: t, s
func (_m *Logger) Log(t time.Time, s string) {
	_m.Called(t, s)
}
